### ISSUE TITLE
Using S command twice too quickly

### ISSUE THREAD

**Issue by eugeniodilo** [marcsosduma/cobgdb#13]
if you type the S command twice too quickly the debugger freezes and remains frozen. 

see attached screen.
![image](https://github.com/marcsosduma/cobgdb/assets/13390725/985a4672-000f-4583-b2a8-3ad2966d2abd)

**Comment by eugeniodilo** [comment]
same problem if you hold "S" key  for 1 or 2 seconds without releasing it

**Comment by marcsosduma** [comment]
Hello! I believe it has been resolved.

**Comment by eugeniodilo** [comment]
I'm sorry but now with this new version I can no longer download the cobgdb.exe file. 
When I try to download my Windows 10 system tells me it detects a virus and doesn't download.

**Comment by marcsosduma** [comment]
Hello Professor Eugenio! I will try...

**Comment by marcsosduma** [comment]
A tip...
Since you already have GnuCOBOL installed, the necessary programs to generate the executable are already available: gcc.exe and mingw32-make.exe
To generate cobgdb.exe, it's very simple:

1. Download the project (via zip or git):
  ` git clone https://github.com/marcsosduma/cobgdb.git`
2. Enter the directory:
   `cd cobgdb`
3. Execute the make command:
   `mingw32-make`

**Comment by eugeniodilo** [comment]
Ok. this worked ! (downloaded the project as ZIP)

![image](https://github.com/marcsosduma/cobgdb/assets/13390725/60a4415b-6bc5-4c68-9d25-752c0e8f7822)

**Comment by eugeniodilo** [comment]
Bug on S command solved.
